export const album = [
  {
    id: 0,
    album: "OST",
    name: "My Love",
    image: "/images/mylove.webp",
    color: "myl-ove",
    date: "2020. 09. 22.",
    link: "",
  },
  {
    id: 1,
    album: "DIGITAL SINGLE",
    name: "Autumn Memories",
    image: "/images/digital_single.webp",
    color: "digital-single",
    date: "2021. 09. 23.",
  },
  {
    id: 2,
    album: "SINGLE 1",
    name: "Glassy",
    image: "/images/single1.webp",
    color: "single-1",
    date: "2021. 10. 07.",
  },
  {
    id: 3,
    album: "MINI 1",
    name: "Op.22 Y-Waltz : in Major",
    image: "/images/mini1.webp",
    color: "mini-1",
    date: "2022. 06. 02.",
  },
  {
    id: 4,
    album: "MAYBE",
    name: "MAYBE",
    image: "/images/maybe.webp",
    color: "digital-single-2",
    date: "2022. 08. 11.",
  },
  {
    id: 5,
    album: "YELLOW CIRCLE",
    name: "Yellow Circle",
    image: "/images/yellowcircle.webp",
    color: "digital-single-4",
    date: "2023. 07. 05.",
  },
  {
    id: 6,
    album: "SINGLE 2",
    name: "Op.22 Y-Waltz : in Minor",
    image: "/images/single2.webp",
    color: "single-2",
    date: "2022. 10. 24.",
  },
  {
    id: 7,
    album: "REINTERPRETATION",
    name: "A Poem Titled You",
    image: "/images/reinterpret.webp",
    color: "digital-single-3",
    date: "2023. 07. 05.",
  },
  {
    id: 8,
    album: "MINI 2",
    name: "LOVE ALL",
    image: "/images/mini2.webp",
    color: "mini-2",
    date: "2023. 08. 09.",
  },
];
